apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: honey-istio
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: honey-istio
    spec:
      containers:
      - env:
        - name: LOG_HOST
          value: {{MYDESTNAME}}
        #image: kiodo/honeyplus80
        image: kiodo/honey80http
        name: honey-istio
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
status: {}
