apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    name: honeypot
  name: honeypot
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
    nodePort: 30005
  selector:
    name: honeypot
  type: NodePort
