apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    name: nginxproxy
  name: nginxproxy
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
    nodePort: 30080
  selector:
    name: nginxproxy
  type: NodePort
