apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    name: nginxproxy
  name: nginxproxy
spec:
  ports:
  - name: "8000"
    port: 8000
    targetPort: 8000
    nodePort: 30080
  selector:
    name: nginxproxy
  type: NodePort
